Repository kevporti/TeamsManager, pull requests merged in 2022-12, with the labels that each got.

#1 Nextauth
  package-lock.json
  package.json
Labels: authentication

#3 Database work
  prisma/migrations/20221205224210_first_migration/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: enhancement

#23 Nextauth
  .env.example
Labels: bug

#26 Database work
  prisma/schema.prisma
Labels: help wanted
